### ISSUE TITLE
Explanation how to run a CLI project in pycharm community 

### ISSUE THREAD

**Issue by sephib** [mikeckennedy/python-for-entrepreneurs-course-demos#1]
Hi,
Just thought that you may want to add the instructions how to run a CLI pyramid project in pycharm community addition. (after running the CLI commands)

In windows it was something of this sort

1. Add local virtual environment to project settings / interpreter  Drive:\Full_path_to_folder\virtualenv\blueyellow\Scripts\python.exe
2. edit configuration for running project:
2.1. Script: Drive:\Full_path_to_folder\virtualenv\blueyellow\Scripts\pserve-script.py
2.2. Script parameters Drive:\Full_path_to_folder\blue_yellow_app\development.ini

**Comment by mikeckennedy** [comment]
Yep, that sounds about right. How about this?

https://training.talkpython.fm/player/course/python-for-entrepreneurs-build-and-launch-your-online-business/lecture/50410

:)

**Comment by mikeckennedy** [comment]
And for those of you without access:

https://youtu.be/_acAGHV4YZs

**Comment by sephib** [comment]
yup - looks good.
great response time!

**Comment by mikeckennedy** [comment]
Great, I did seem to omit windows, but hopefully the ideas and commands translate closely enough.
