### ISSUE TITLE
Need support for bare domains e.g. example.com

### ISSUE THREAD

**Issue by scrubbs** [mikeckennedy/python-for-entrepreneurs-course-demos#19]
bare domain names example.com are not supported in deployment. pull request with a fix is proposed separately.

**Comment by scrubbs** [comment]
pull request complete

**Comment by mikeckennedy** [comment]
Thanks @scrubbs ! @mattmakai can you have a look a this? I believe it's from your section.

**Comment by mattmakai** [comment]
hey @scrubbs, thanks for taking the time to add this bit in the playbook. However, I strongly recommend against naked domains as they have significant disadvantages with regards to cookies and SEO. This also add an additional configuration that's not shown in the videos which could confuse folks who take the course. I'd prefer to leave this out, but I'm open to listening if really feel it should be added to the playbook.

**Comment by scrubbs** [comment]
Not a problem Matt. You have a stronger opinion than I do and I don't know the SEO implications. I appreciate the consideration. I'll close and look up the implications on the web.

**Comment by mattmakai** [comment]
sounds good Chris. here are a couple of resources that have reasonably good explanations for why you'd want to avoid the naked domain route: [setting cookies only on the naked domain](https://webmasters.stackexchange.com/questions/55790/setting-cookies-only-on-the-naked-domain) and [WWW or bare domain?](http://www.greenhills.co.uk/2011/06/12/www-or-bare-domain.html)

**Comment by scrubbs** [comment]
Thanks Matt
