### ISSUE TITLE
'clear' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ianmonat** [mikeckennedy/python-for-entrepreneurs-course-demos#2]
Hi Michael, 

I'm just starting your Python for Entrepreneurs course and am enjoying it so far. 

I just finished the Python language refresher game and although my code runs, it contains this message about the word 'clear'. (see below)

I tried copying your code from github into my file and the message still displays, so I don't think it's a bug in my code, but perhaps some system setting that needs changing. I'm on Windows 7 and using PyCharm. 

Couldn't find the exact fix on Stackoverflow so I thought I'd ask you how to get rid of it, it's more annoying than anything. Thank you. -Ian 

```
C:\Users\imonat\AppData\Local\Programs\Python\Python35-32\python.exe C:/Users/imonat/Desktop/Python_Scripts/PyForEnt/program.py
'clear' is not recognized as an internal or external command,
operable program or batch file.
Blue  'clear' is not recognized as an internal or external command,
operable program or batch file.
1 moves:
Next [r,g,b,y]: b
'clear' is not recognized as an internal or external command,
operable program or batch file.
Blue  Yellow  'clear' is not recognized as an internal or external command,
operable program or batch file.
2 moves:
Next [r,g,b,y]: b
Next [r,g,b,y]: y
'clear' is not recognized as an internal or external command,
operable program or batch file.
Blue  Yellow  Yellow  'clear' is not recognized as an internal or external command,
operable program or batch file.
3 moves:
Next [r,g,b,y]: r
Sorry, that was wrong
Game over

Process finished with exit code 0
```

**Comment by mikeckennedy** [comment]
Hi,

The error is because I didn't check whether you're on Windows or a *nix based system. If you change `clear` to `cls` it will work.

**Comment by mikeckennedy** [comment]
The most recent check-in fixes the issue:

def clear(self):
    if os.name == 'nt':
        os.system('cls')
    else:
        os.system('clear')

**Comment by mikeckennedy** [comment]
Thanks for letting me know about this error.
