### ISSUE TITLE
Template variations / inconsistencies video is not showing up.

### ISSUE THREAD

**Issue by elforce001** [mikeckennedy/python-for-entrepreneurs-course-demos#22]
Hi Mike, 

I'm having an issue with this video. All others are working fine except the one:
"Build web apps with Pyramid: Part 1: Template variations / inconsistencies"

Regards,

**Comment by elforce001** [comment]
Hi Mike,

The only videos I can play are the ones I've seen. 

Regards,

**Comment by elforce001** [comment]
I don't know why, but after I clicked "resume course", the videos started playing.

Best regards,

**Comment by mikeckennedy** [comment]
Glad it's back. Not sure what was up. :)
