### ISSUE TITLE
SSL cert for deployment is off?

### ISSUE THREAD

**Issue by mikeckennedy** [mikeckennedy/python-for-entrepreneurs-course-demos#25]
Hi @mattmakai , have a look at 

https://www.pythondeploymentexample.com/

What do you think is up with the ssl cert?

**Comment by stevepiercy** [comment]
It expired:

Expired: Friday, June 9, 2017 at 6:03:00 PM Pacific Daylight Time

Did you add a cron job to automatically renew? There's also certbot instructions for nginx on Ubuntu (not sure of your version), if you used it to install the cert:
https://certbot.eff.org/#ubuntuxenial-nginx

**Comment by mikeckennedy** [comment]
Thanks Steve. That was my guess too. That the cron job didn't / doesn't run.

**Comment by mattmakai** [comment]
hmm yea cert needs renewal, thanks for the heads up @stevepiercy. will fix as soon as I can

**Comment by mikeckennedy** [comment]
Thanks for fixing this Matt. :)
