### ISSUE TITLE
Cannot resolve directory 'static' in PyCharm Professional

### ISSUE THREAD

**Issue by jaylaw** [mikeckennedy/python-for-entrepreneurs-course-demos#27]
I am having a problem with PyCharm using relative imports in my template files. I have found resources that provide solutions for a Django project. I have not been able to find anything specific about Pyramid projects. It would be helpful if I could see affected css tags when highlighting in the template as I see in your videos.

**Comment by mikeckennedy** [comment]
Hi Jay,

There is problem something like this:

``` <link href="${request.static_url('packagename:static/theme.css')}" rel="stylesheet">```

This is basically useless but often causes trouble. Just put this instead:

``` <link href="/static/theme.css" rel="stylesheet">```

**Comment by jaylaw** [comment]
Thanks! That seemed to work. PyCharm still highlights the as unresolved, but I have the breadcrumbs, at least. If I climb up one directory:

`<link href="../static/theme.css" rel="stylesheet">`

the warning goes away.

![image](https://user-images.githubusercontent.com/420089/32962703-f2b730ba-cb79-11e7-9451-07b5050cc4cc.png)

**Comment by mikeckennedy** [comment]
Yeah, that's annoying that it does that. To fix the missing static files, right click on the folder containing static, and choose mark directory as "resources root". Then it will find them.

**Comment by jaylaw** [comment]
That did it! Thanks a lot! I really appreciate the work you put into your podcast and courses. They have taught me a lot.

**Comment by mikeckennedy** [comment]
Great and you're welcome Jay!
