### ISSUE TITLE
cookiecutter not working on mac

### ISSUE THREAD

**Issue by alexfowler** [mikeckennedy/python-for-entrepreneurs-course-demos#29]
when I try to run the following cookiecutter command: 
`cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter`

I get the following error:

> Traceback (most recent call last):
>   File "/Users/afowler/Desktop/test_project/.env/bin/cookiecutter", line 11, in <module>
>     sys.exit(main())
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/cookiecutter/cli.py", line 120, in main
>     password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
>     password=password
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/cookiecutter/repository.py", line 103, in determine_repo_dir
>     no_input=no_input,
>   File "/Users/afowler/Desktop/test_project/.env/lib/python3.6/site-packages/cookiecutter/vcs.py", line 99, in clone
>     stderr=subprocess.STDOUT,
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/Pylons/pyramid-cookiecutter-starter']' returned non-zero exit status 1.

I'm using Python 3.6.3 and Mac OS High Sierra version 10.13.2. Any idea what the problem could be?

**Comment by stevepiercy** [comment]
It looks like you installed cookiecutter into your virtual environment, and had activated it. Is that correct?

The stack trace means `git clone https://github.com/Pylons/pyramid-cookiecutter-starter` failed. It could have been a temporary network glitch or GitHub outage. That command should work, unless you lack permissions to write into the location where you invoked cookiecutter.

There's a SO post that can help you examine the error:
https://stackoverflow.com/questions/27920837/python-subprocess-check-output-returned-non-zero-exit-status-1

**Comment by mikeckennedy** [comment]
It's also possible that git is either not installed or not in the path.
What happens when you type `git` on the command line?

**Comment by alexfowler** [comment]
@stevepiercy I get the same error even when I run the command from outside of my virtual environment

@mikeckennedy when i typed `git` on the command line i got the following error:

> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

When googling the error, I came across this [stackoverflow solution](https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path) and it seems like it has to do with needing to download and install xcode developer tools when you upgrade to macOs Sierra!  Nice tip @mikeckennedy !
