### ISSUE TITLE
CookieCutter error... didnt say to install zsh

### ISSUE THREAD

**Issue by datatalking** [mikeckennedy/python-for-entrepreneurs-course-demos#30]
As a new python user I wouldn't know to install zsh and I'm currently not using it but even once I do install cookie cutter the 'cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter' command isn't working.

-bash: cookiecutter: command not found
If zsh is required then the course needs to be amended or notes for bash users.

"we don't know what we don't know"

**Comment by mikeckennedy** [comment]
Hi @datatalking 

I wonder if it's Python in the path sort of thing. What do you get when you type this in the terminal / command prompt:

Linux/mac: `which python3`
windows: `where python`

If that succeeds, they try

Linux/mac: `python3 -m cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter`
windows: `python -m cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter`

**Comment by datatalking** [comment]
Hi Mike,

The Linux/mac CLI code you provided worked, why is that required or what does it do. 

My 'which python3' gave me.
/Users/owner/miniconda3/bin/python3

Thanks for the update.

**Comment by mikeckennedy** [comment]
Hi @datatalking 

I don't know if I said this before, but bash is totally fine. ZSH is just what I happen to use.

I wonder if for some reason when you installed cookiecutter it was installed into the user path for miniconda and that isn't in your path?

Tryp typing python3 -m cookiecutter and see what happens. Like I said before:

If that succeeds, they try

Linux/mac: `python3 -m cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter`
windows: `python -m cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter`

May need pip installed into that [Python env first](https://pip.pypa.io/en/stable/installing/).

**Comment by datatalking** [comment]
Thanks, in the Python for entreprenuers course on Pyramid, at the step where it says "Build web apps with Pyramid: Applied web development"... can you link me to where that app was built I've gotten lost in all the links.

**Comment by mikeckennedy** [comment]
Hi @datatalking sure thing. There are two folders here. One is where we started in that chapter, the other where we ended.

https://github.com/mikeckennedy/python-for-entrepreneurs-course-demos/tree/master/04-applied-web

Best,
Michael
