### ISSUE TITLE
static_cache.py was using incorrect path

### ISSUE THREAD

**Issue by lijia00** [mikeckennedy/python-for-entrepreneurs-course-demos#33]
Hi,

I had to modify the code in the static_cache.py file because the variable __full_path was giving the directory as blue_yellow_app/infrastructure. When it goes to build the cache ID here below, it looks for the relative url given in the templates as /static/**** and joins it, giving a fullname = /blue_yellow_app/infrastructure/static/*** - and the .css files are not there. 

fullname = os.path.abspath(os.path.join(
        __full_path, relative_file_url.lstrip('/')))

i modified the code to look for the files one more directory up where /static is by calling os.path.dirname on the __full_path variable like so:

__full_path = os.path.dirname(os.path.abspath(__file__))
__base_path = os.path.dirname(__full_path)

**Comment by mikeckennedy** [comment]
Hi @lijia00 Sorry you ran into trouble. 

I don't think you need to do this. I just checked out the code fresh and ran chapter 17 final on a new environment and the static files were fine. All the cache id's were there.

I think this must be something about how you're running the code. Is it possible that you're using the wrong working directory or something like this?

When I run the code as is and print out the full path, I get:

`/Users/mkennedy/Desktop/pfe/17_logging_and_monitoring/final_17_blue_yellow_app_monitoring/blue_yellow_app`

Doing an `ls /Users/mkennedy/Desktop/pfe/17_logging_and_monitoring/final_17_blue_yellow_app_monitoring/blue_yellow_app/static` shows that it is there.
