### ISSUE TITLE
bower install bootstrap-css version issue

### ISSUE THREAD

**Issue by danshorstein** [mikeckennedy/python-for-entrepreneurs-course-demos#5]
When you use bower install bootstrap-css, it gives you bootstrap-css version 3.3.6. However when I tried downloading and using the startbootstrap template, the navbar collapsing wasn't working; I checked and noticed the download zipfile from bootstrap includes bootstrap-css version 3.3.7. When I dropped in 3.3.7 instead of 3.3.6 into pycharm, the nav bar started working properly. I'm not sure if there's another way to use Bower to get the latest bootstrap-css version, but thought this was an issue worth sharing. I opened an issue on the bower-bootstrap-css github on this, so hopefully they'll just fix it there.

**Comment by mikeckennedy** [comment]
Thanks. With bower you should be able to be in the static dir and just run

`bower update`

This may require tweaking CSS/JS links the html if the filenames change (not sure if they do).

I'll see about updating it in the main repo.

Thanks!
Michael

**Comment by danshorstein** [comment]
Right, you *should* be able to do that with Bower. But that's where the
problem is. I tried using bower update - and Bower thinks that 3.3.6 is the
most updated version. But the start bootstrap uses 3.3.7. And my hamburger
menu only worked when I manually replaced the bootstrap.min.css file with
the 3.3.7 version.

[image: pasted1]

On Mon, Feb 27, 2017 at 10:09 AM Michael Kennedy <notifications@github.com>
wrote:

Thanks. With bower you should be able to be in the static dir and just run

bower update

This may require tweaking CSS/JS links the html if the filenames change
(not sure if they do).

I'll see about updating it in the main repo.

Thanks!
Michael

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mikeckennedy/python-for-entrepreneurs-course-demos/issues/5#issuecomment-282746813>,
or mute the thread

**Comment by danshorstein** [comment]
I think one solution could be this
https://libraries.io/bower/components-bootstrap/3.3.7

Instead of bower install bootstrap-css  , you could use bower install
components-bootstrap#3.3.7

**Comment by danshorstein** [comment]
Looks like the github repo behind install bootstrap-css has been updated to include css 3.3.7, so all is good now!
